import type { AppBuilderProject } from '../../project/schema/types'
import { generateHtmlProject } from '../html/generateProject'

export interface ReactProject {
  files: Record<string, string>
}

/** A real, runnable React + Vite project. To stay honest about scope: page
 * markup is generated from the same tree/style engine as the HTML export
 * (proven correct there) and mounted via one React component per page,
 * rather than re-deriving a full idiomatic JSX tree for every component
 * type — the interaction runtime is the same small vanilla engine the
 * static HTML export uses, wired up through a useEffect. It's a genuine
 * React app you can `npm run dev` / build, not a relabelled static export. */
export function generateReactProject(project: AppBuilderProject): ReactProject {
  const { html, css, js } = generateHtmlProject(project)
  const pageEntries = Object.entries(html)
  const isMobile = project.target === 'mobile'

  const bodyOf = (fullHtml: string) => {
    const match = fullHtml.match(/<body>([\s\S]*)<script/)
    return (match ? match[1] : fullHtml).trim()
  }

  const pagesObject = pageEntries
    .map(([filename, content], i) => `  ${JSON.stringify(filename)}: ${JSON.stringify(bodyOf(content))}${i < pageEntries.length - 1 ? ',' : ''}`)
    .join('\n')

  const appJsx = `import { useEffect, useRef, useState } from 'react'
import './style.css'
import { initRuntime } from './runtime.js'

const PAGES = {
${pagesObject}
}

const INITIAL_PAGE = ${JSON.stringify(isMobile ? Object.keys(html)[0] : Object.keys(html)[0])}

export default function App() {
  const [page, setPage] = useState(INITIAL_PAGE)
  const containerRef = useRef(null)

  useEffect(() => {
    // Re-wiring on every page change re-attaches click/input listeners to
    // the newly-mounted markup (dangerouslySetInnerHTML swaps the DOM out
    // from under React on navigation, so nothing carries listeners over).
    const cleanup = initRuntime(setPage)
    return cleanup
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page])

  return <div ref={containerRef} dangerouslySetInnerHTML={{ __html: PAGES[page] || '' }} />
}
`

  const mainJsx = `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`

  // The runtime is the same interpreter as the static export, adapted to
  // call back into React state for page navigation instead of toggling
  // `.active` classes directly (React owns what's mounted here).
  const runtimeJs = js
    .replace('function showScreen(pageId) {', 'let reactSetPage = null;\nfunction showScreen(pageId) {\n    if (reactSetPage) reactSetPage(pageId);')
    .replace(
      '(function () {',
      'export function initRuntime(setPage) {\n  reactSetPage = setPage;',
    )
    .replace(/}\)\(\);\s*$/, '  return function () { reactSetPage = null; };\n}')
    .replace('var IS_SPA = ' + isMobile + ';', `var IS_SPA = ${isMobile};`)

  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${project.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`

  const packageJson = {
    name: project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'app',
    private: true,
    version: '0.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
    devDependencies: { '@vitejs/plugin-react': '^4.3.1', vite: '^5.4.1' },
  }

  const viteConfig = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({ plugins: [react()] })
`

  const readme = `# ${project.name}\n\nA React + Vite project generated by Threesy App Builder.\n\n## Run it\n\n\`\`\`\nnpm install\nnpm run dev\n\`\`\`\n`

  return {
    files: {
      'package.json': JSON.stringify(packageJson, null, 2),
      'vite.config.js': viteConfig,
      'index.html': indexHtml,
      'README.md': readme,
      'src/main.jsx': mainJsx,
      'src/App.jsx': appJsx,
      'src/runtime.js': runtimeJs,
      'src/style.css': css,
    },
  }
}
