import type { AppBuilderProject } from '../../project/schema/types'
import { generateHtmlProject } from '../html/generateProject'

function slug(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'page'
}

function toFlaskTemplate(htmlText: string): string {
  return htmlText
    .replace('href="style.css"', `href="{{ url_for('static', filename='style.css') }}"`)
    .replace('src="script.js"', `src="{{ url_for('static', filename='script.js') }}"`)
}

export interface FlaskProject {
  appPy: string
  templates: Record<string, string>
  staticCss: string
  staticJs: string
  readme: string
}

/** A real, runnable Flask project generated from the same component tree —
 * not a claim that the mobile UI "becomes" Python. For mobile projects this
 * is explicitly a backend starter, not a native UI generator. */
export function generateFlaskProject(project: AppBuilderProject): FlaskProject {
  const { html, css, js } = generateHtmlProject(project)
  const templates: Record<string, string> = {}
  const routes: string[] = []

  for (const [filename, content] of Object.entries(html)) {
    templates[filename] = toFlaskTemplate(content)
    const routePath = filename === 'index.html' ? '/' : `/${slug(filename.replace('.html', ''))}`
    const fnName = `page_${slug(filename.replace('.html', '')).replace(/-/g, '_')}`
    routes.push(`@app.route('${routePath}')\ndef ${fnName}():\n    return render_template('${filename}')\n`)
  }

  const appPy = `from flask import Flask, render_template

app = Flask(__name__)

${routes.join('\n')}
if __name__ == '__main__':
    app.run(debug=True)
`

  const readme =
    project.target === 'web'
      ? `# ${project.name}\n\nA Flask project generated by Threesy App Builder.\n\n## Run it\n\n\`\`\`\npip install flask\npython app.py\n\`\`\`\n`
      : `# ${project.name} — Backend Starter\n\nThreesy's Python export gives your mobile app a Flask **backend** starter —\nit does not attempt to turn your screens into native mobile UI. Use this\nfor an API your exported app (Web/PWA, React Native, or Expo) can call.\n\n## Run it\n\n\`\`\`\npip install flask\npython app.py\n\`\`\`\n`

  return { appPy, templates, staticCss: css, staticJs: js, readme }
}
